CREATE TABLE users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email VARCHAR(100) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
    phone_number VARCHAR(20),
    first_name VARCHAR(50),
    last_name VARCHAR(50),
    avatar VARCHAR(500),
    role VARCHAR(20) NOT NULL,
    enabled BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP,
    CONSTRAINT ck_users_role
        CHECK (role IN ('CUSTOMER', 'COURT_OWNER', 'ADMIN')),
    CONSTRAINT ck_users_timestamps
        CHECK (updated_at IS NULL OR updated_at >= created_at)
);

CREATE TABLE sport_types (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100) NOT NULL UNIQUE
);

CREATE TABLE venues (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(150) NOT NULL,
    address VARCHAR(255) NOT NULL,
    latitude NUMERIC(10, 7),
    longitude NUMERIC(10, 7),
    banner VARCHAR(500),
    logo VARCHAR(500),
    status VARCHAR(30) NOT NULL DEFAULT 'PENDING',
    owner_id BIGINT NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP,
    CONSTRAINT fk_venues_owner
        FOREIGN KEY (owner_id) REFERENCES users (id),
    CONSTRAINT ck_venues_status
        CHECK (status IN ('ACTIVE', 'INACTIVE', 'PENDING', 'REJECTED')),
    CONSTRAINT ck_venues_coordinates
        CHECK (
            (latitude IS NULL OR latitude BETWEEN -90 AND 90)
            AND (longitude IS NULL OR longitude BETWEEN -180 AND 180)
        ),
    CONSTRAINT ck_venues_timestamps
        CHECK (updated_at IS NULL OR updated_at >= created_at)
);

CREATE TABLE benefits (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    venue_id BIGINT NOT NULL,
    CONSTRAINT fk_benefits_venue
        FOREIGN KEY (venue_id) REFERENCES venues (id) ON DELETE CASCADE
);

CREATE TABLE rules (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    venue_id BIGINT NOT NULL,
    CONSTRAINT fk_rules_venue
        FOREIGN KEY (venue_id) REFERENCES venues (id) ON DELETE CASCADE
);

CREATE TABLE venue_images (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    url VARCHAR(500) NOT NULL,
    venue_id BIGINT NOT NULL,
    CONSTRAINT fk_venue_images_venue
        FOREIGN KEY (venue_id) REFERENCES venues (id) ON DELETE CASCADE
);

CREATE TABLE courts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    price_per_hour NUMERIC(12, 2) NOT NULL,
    status VARCHAR(30) NOT NULL DEFAULT 'ACTIVE',
    venue_id BIGINT NOT NULL,
    sport_type_id BIGINT NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP,
    CONSTRAINT fk_courts_venue
        FOREIGN KEY (venue_id) REFERENCES venues (id) ON DELETE CASCADE,
    CONSTRAINT fk_courts_sport_type
        FOREIGN KEY (sport_type_id) REFERENCES sport_types (id),
    CONSTRAINT ck_courts_status
        CHECK (status IN ('ACTIVE', 'INACTIVE', 'MAINTENANCE')),
    CONSTRAINT ck_courts_price
        CHECK (price_per_hour > 0),
    CONSTRAINT ck_courts_timestamps
        CHECK (updated_at IS NULL OR updated_at >= created_at)
);

CREATE TABLE hero_banners (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    url VARCHAR(500) NOT NULL,
    target_url VARCHAR(500),
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP,
    CONSTRAINT ck_hero_banners_timestamps
        CHECK (updated_at IS NULL OR updated_at >= created_at)
);

CREATE TABLE bookings (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_id BIGINT NOT NULL,
    court_id BIGINT NOT NULL,
    booking_date DATE NOT NULL,
    start_time TIME NOT NULL,
    end_time TIME NOT NULL,
    total_price NUMERIC(12, 2) NOT NULL,
    required_deposit NUMERIC(12, 2) NOT NULL,
    status VARCHAR(30) NOT NULL DEFAULT 'PENDING',
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP,
    CONSTRAINT fk_bookings_customer
        FOREIGN KEY (customer_id) REFERENCES users (id),
    CONSTRAINT fk_bookings_court
        FOREIGN KEY (court_id) REFERENCES courts (id),
    CONSTRAINT ck_bookings_status
        CHECK (status IN ('PENDING', 'CONFIRMED', 'COMPLETED', 'EXPIRED')),
    CONSTRAINT ck_bookings_time
        CHECK (start_time < end_time),
    CONSTRAINT ck_bookings_amounts
        CHECK (
            total_price > 0
            AND required_deposit > 0
            AND required_deposit <= total_price
        ),
    CONSTRAINT ck_bookings_timestamps
        CHECK (updated_at IS NULL OR updated_at >= created_at)
);

CREATE TABLE owner_payment_accounts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    owner_id BIGINT NOT NULL,
    provider VARCHAR(30) NOT NULL,
    status VARCHAR(30) NOT NULL DEFAULT 'PENDING',
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP,
    CONSTRAINT fk_payment_accounts_owner
        FOREIGN KEY (owner_id) REFERENCES users (id),
    CONSTRAINT uq_payment_accounts_owner_provider
        UNIQUE (owner_id, provider),
    CONSTRAINT ck_payment_accounts_provider
        CHECK (provider IN ('MOMO', 'VNPAY')),
    CONSTRAINT ck_payment_accounts_status
        CHECK (status IN ('PENDING', 'ACTIVE', 'INACTIVE', 'SUSPENDED')),
    CONSTRAINT ck_payment_accounts_timestamps
        CHECK (updated_at IS NULL OR updated_at >= created_at)
);

CREATE TABLE momo_credentials (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    payment_account_id BIGINT NOT NULL UNIQUE,
    partner_code VARCHAR(100) NOT NULL UNIQUE,
    access_key VARCHAR(500) NOT NULL,
    secret_key VARCHAR(500) NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP,
    CONSTRAINT fk_momo_credentials_account
        FOREIGN KEY (payment_account_id)
        REFERENCES owner_payment_accounts (id) ON DELETE CASCADE,
    CONSTRAINT ck_momo_credentials_timestamps
        CHECK (updated_at IS NULL OR updated_at >= created_at)
);

CREATE TABLE vnpay_credentials (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    payment_account_id BIGINT NOT NULL UNIQUE,
    tmn_code VARCHAR(100) NOT NULL UNIQUE,
    hash_secret VARCHAR(500) NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP,
    CONSTRAINT fk_vnpay_credentials_account
        FOREIGN KEY (payment_account_id)
        REFERENCES owner_payment_accounts (id) ON DELETE CASCADE,
    CONSTRAINT ck_vnpay_credentials_timestamps
        CHECK (updated_at IS NULL OR updated_at >= created_at)
);

CREATE TABLE payments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    booking_id BIGINT NOT NULL,
    payment_account_id BIGINT,
    amount NUMERIC(12, 2) NOT NULL,
    payment_type VARCHAR(30) NOT NULL,
    status VARCHAR(30) NOT NULL DEFAULT 'PENDING',
    payment_method VARCHAR(30) NOT NULL,
    transaction_code VARCHAR(255) UNIQUE,
    paid_at TIMESTAMP,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP,
    CONSTRAINT fk_payments_booking
        FOREIGN KEY (booking_id) REFERENCES bookings (id) ON DELETE CASCADE,
    CONSTRAINT fk_payments_account
        FOREIGN KEY (payment_account_id) REFERENCES owner_payment_accounts (id),
    CONSTRAINT ck_payments_type
        CHECK (payment_type IN ('DEPOSIT', 'REMAINING', 'FULL_PAYMENT')),
    CONSTRAINT ck_payments_status
        CHECK (status IN ('PENDING', 'PAID', 'FAILED', 'EXPIRED')),
    CONSTRAINT ck_payments_method
        CHECK (payment_method IN ('CASH', 'VNPAY', 'MOMO')),
    CONSTRAINT ck_payments_amount
        CHECK (amount > 0),
    CONSTRAINT ck_payments_paid_at
        CHECK (
            (status = 'PAID' AND paid_at IS NOT NULL)
            OR (status IN ('PENDING', 'FAILED', 'EXPIRED') AND paid_at IS NULL)
        ),
    CONSTRAINT ck_payments_timestamps
        CHECK (
            (updated_at IS NULL OR updated_at >= created_at)
            AND (paid_at IS NULL OR paid_at >= created_at)
        )
);

CREATE INDEX idx_venues_status ON venues (status);
CREATE INDEX idx_venues_owner ON venues (owner_id);
CREATE INDEX idx_venues_lower_name ON venues (LOWER(name));
CREATE UNIQUE INDEX uq_sport_types_lower_name ON sport_types (LOWER(name));
CREATE UNIQUE INDEX uq_benefits_venue_lower_name ON benefits (venue_id, LOWER(name));
CREATE UNIQUE INDEX uq_rules_venue_lower_name ON rules (venue_id, LOWER(name));
CREATE INDEX idx_courts_venue ON courts (venue_id);
CREATE INDEX idx_courts_sport_type ON courts (sport_type_id);
CREATE INDEX idx_bookings_customer ON bookings (customer_id);
CREATE INDEX idx_bookings_court_date ON bookings (court_id, booking_date);
CREATE INDEX idx_bookings_status ON bookings (status);
CREATE INDEX idx_payments_booking ON payments (booking_id);
CREATE INDEX idx_payments_account ON payments (payment_account_id);
CREATE INDEX idx_payments_status ON payments (status);
CREATE INDEX idx_payment_accounts_owner ON owner_payment_accounts (owner_id);

INSERT INTO sport_types (name) VALUES
    ('Bóng đá'),
    ('Cầu lông'),
    ('Pickleball'),
    ('Tennis'),
    ('Bóng rổ'),
    ('Bóng chuyền');

INSERT INTO users (
    email, password, phone_number, first_name, last_name, avatar, role,
    enabled, created_at, updated_at
) VALUES
    ('admin@fieldmate.local', '$2a$10$KbQiHKTa1WIsQFTQWQKCiujoTJJB7MCMSaSgG/imVkKRicMPwgN5i', '0901000001', 'Quản trị', 'FieldMate', 'https://robohash.org/fieldmate-admin-avatar.png', 'ADMIN', TRUE, CURRENT_TIMESTAMP - INTERVAL '180 days', CURRENT_TIMESTAMP - INTERVAL '180 days'),
    ('owner1@fieldmate.local', '$2a$10$KbQiHKTa1WIsQFTQWQKCiujoTJJB7MCMSaSgG/imVkKRicMPwgN5i', '0902000001', 'Minh', 'An', 'https://robohash.org/fieldmate-owner-one-avatar.png', 'COURT_OWNER', TRUE, CURRENT_TIMESTAMP - INTERVAL '170 days', CURRENT_TIMESTAMP - INTERVAL '170 days'),
    ('owner2@fieldmate.local', '$2a$10$KbQiHKTa1WIsQFTQWQKCiujoTJJB7MCMSaSgG/imVkKRicMPwgN5i', '0902000002', 'Khánh', 'Linh', 'https://robohash.org/fieldmate-owner-two-avatar.png', 'COURT_OWNER', TRUE, CURRENT_TIMESTAMP - INTERVAL '165 days', CURRENT_TIMESTAMP - INTERVAL '165 days'),
    ('owner3@fieldmate.local', '$2a$10$KbQiHKTa1WIsQFTQWQKCiujoTJJB7MCMSaSgG/imVkKRicMPwgN5i', '0902000003', 'Hoàng', 'Nam', 'https://robohash.org/fieldmate-owner-three-avatar.png', 'COURT_OWNER', TRUE, CURRENT_TIMESTAMP - INTERVAL '160 days', CURRENT_TIMESTAMP - INTERVAL '160 days'),
    ('owner4@fieldmate.local', '$2a$10$KbQiHKTa1WIsQFTQWQKCiujoTJJB7MCMSaSgG/imVkKRicMPwgN5i', '0902000004', 'Thảo', 'Vy', 'https://robohash.org/fieldmate-owner-four-avatar.png', 'COURT_OWNER', TRUE, CURRENT_TIMESTAMP - INTERVAL '155 days', CURRENT_TIMESTAMP - INTERVAL '155 days'),
    ('owner5@fieldmate.local', '$2a$10$KbQiHKTa1WIsQFTQWQKCiujoTJJB7MCMSaSgG/imVkKRicMPwgN5i', '0902000005', 'Quang', 'Duy', 'https://robohash.org/fieldmate-owner-five-avatar.png', 'COURT_OWNER', TRUE, CURRENT_TIMESTAMP - INTERVAL '150 days', CURRENT_TIMESTAMP - INTERVAL '150 days'),
    ('owner6@fieldmate.local', '$2a$10$KbQiHKTa1WIsQFTQWQKCiujoTJJB7MCMSaSgG/imVkKRicMPwgN5i', '0902000006', 'Thu', 'Hà', 'https://robohash.org/fieldmate-owner-six-avatar.png', 'COURT_OWNER', TRUE, CURRENT_TIMESTAMP - INTERVAL '145 days', CURRENT_TIMESTAMP - INTERVAL '145 days'),
    ('owner7@fieldmate.local', '$2a$10$KbQiHKTa1WIsQFTQWQKCiujoTJJB7MCMSaSgG/imVkKRicMPwgN5i', '0902000007', 'Phúc', 'Khang', 'https://robohash.org/fieldmate-owner-seven-avatar.png', 'COURT_OWNER', TRUE, CURRENT_TIMESTAMP - INTERVAL '140 days', CURRENT_TIMESTAMP - INTERVAL '140 days'),
    ('customer1@fieldmate.local', '$2a$10$KbQiHKTa1WIsQFTQWQKCiujoTJJB7MCMSaSgG/imVkKRicMPwgN5i', '0913000001', 'Gia', 'Huy', 'https://robohash.org/fieldmate-customer-one-avatar.png', 'CUSTOMER', TRUE, CURRENT_TIMESTAMP - INTERVAL '120 days', CURRENT_TIMESTAMP - INTERVAL '120 days'),
    ('customer2@fieldmate.local', '$2a$10$KbQiHKTa1WIsQFTQWQKCiujoTJJB7MCMSaSgG/imVkKRicMPwgN5i', '0913000002', 'Bảo', 'Ngọc', 'https://robohash.org/fieldmate-customer-two-avatar.png', 'CUSTOMER', TRUE, CURRENT_TIMESTAMP - INTERVAL '115 days', CURRENT_TIMESTAMP - INTERVAL '115 days'),
    ('customer3@fieldmate.local', '$2a$10$KbQiHKTa1WIsQFTQWQKCiujoTJJB7MCMSaSgG/imVkKRicMPwgN5i', '0913000003', 'Tuấn', 'Kiệt', 'https://robohash.org/fieldmate-customer-three-avatar.png', 'CUSTOMER', TRUE, CURRENT_TIMESTAMP - INTERVAL '110 days', CURRENT_TIMESTAMP - INTERVAL '110 days'),
    ('customer4@fieldmate.local', '$2a$10$KbQiHKTa1WIsQFTQWQKCiujoTJJB7MCMSaSgG/imVkKRicMPwgN5i', '0913000004', 'Mai', 'Chi', 'https://robohash.org/fieldmate-customer-four-avatar.png', 'CUSTOMER', TRUE, CURRENT_TIMESTAMP - INTERVAL '105 days', CURRENT_TIMESTAMP - INTERVAL '105 days'),
    ('customer5@fieldmate.local', '$2a$10$KbQiHKTa1WIsQFTQWQKCiujoTJJB7MCMSaSgG/imVkKRicMPwgN5i', '0913000005', 'Đức', 'Thịnh', 'https://robohash.org/fieldmate-customer-five-avatar.png', 'CUSTOMER', TRUE, CURRENT_TIMESTAMP - INTERVAL '100 days', CURRENT_TIMESTAMP - INTERVAL '100 days'),
    ('customer6@fieldmate.local', '$2a$10$KbQiHKTa1WIsQFTQWQKCiujoTJJB7MCMSaSgG/imVkKRicMPwgN5i', '0913000006', 'Thanh', 'Trúc', 'https://robohash.org/fieldmate-customer-six-avatar.png', 'CUSTOMER', TRUE, CURRENT_TIMESTAMP - INTERVAL '95 days', CURRENT_TIMESTAMP - INTERVAL '95 days'),
    ('customer7@fieldmate.local', '$2a$10$KbQiHKTa1WIsQFTQWQKCiujoTJJB7MCMSaSgG/imVkKRicMPwgN5i', '0913000007', 'Nhật', 'Minh', 'https://robohash.org/fieldmate-customer-seven-avatar.png', 'CUSTOMER', TRUE, CURRENT_TIMESTAMP - INTERVAL '90 days', CURRENT_TIMESTAMP - INTERVAL '90 days'),
    ('customer8@fieldmate.local', '$2a$10$KbQiHKTa1WIsQFTQWQKCiujoTJJB7MCMSaSgG/imVkKRicMPwgN5i', '0913000008', 'Hà', 'My', 'https://robohash.org/fieldmate-customer-eight-avatar.png', 'CUSTOMER', TRUE, CURRENT_TIMESTAMP - INTERVAL '85 days', CURRENT_TIMESTAMP - INTERVAL '85 days'),
    ('customer9@fieldmate.local', '$2a$10$KbQiHKTa1WIsQFTQWQKCiujoTJJB7MCMSaSgG/imVkKRicMPwgN5i', '0913000009', 'Quốc', 'Bảo', 'https://robohash.org/fieldmate-customer-nine-avatar.png', 'CUSTOMER', TRUE, CURRENT_TIMESTAMP - INTERVAL '80 days', CURRENT_TIMESTAMP - INTERVAL '80 days'),
    ('customer10@fieldmate.local', '$2a$10$KbQiHKTa1WIsQFTQWQKCiujoTJJB7MCMSaSgG/imVkKRicMPwgN5i', '0913000010', 'Yến', 'Nhi', 'https://robohash.org/fieldmate-customer-ten-avatar.png', 'CUSTOMER', TRUE, CURRENT_TIMESTAMP - INTERVAL '75 days', CURRENT_TIMESTAMP - INTERVAL '75 days');

INSERT INTO venues (
    name, address, latitude, longitude, banner, logo, status, owner_id,
    created_at, updated_at
)
SELECT seed.name, seed.address, seed.latitude, seed.longitude, seed.banner,
       seed.logo, 'ACTIVE', owner.id, seed.created_at, seed.created_at
FROM (
    VALUES
        ('Sân Pickleball VNA', '39A Hồng Hà, Phường Tân Sơn Hòa, Thành phố Hồ Chí Minh', 10.8132000::NUMERIC, 106.6668000::NUMERIC, 'https://shopvnb.com/uploads/images/san-pickleball-vna-2.jpg', 'https://cdn.shopvnb.com/uploads/images/bai_viet/san-pickleball-vna-5-1731721607.webp', 'owner1@fieldmate.local', CURRENT_TIMESTAMP - INTERVAL '150 days'),
        ('Sân Pickleball ALP', '235/1G An Phú Đông 09, Phường An Phú Đông, Thành phố Hồ Chí Minh', 10.8674000::NUMERIC, 106.6818000::NUMERIC, 'https://shopvnb.com/uploads/tin_tuc/san-pickleball-alp-2_1760302356.jpg', 'https://cdn.shopvnb.com/uploads/images/bai_viet/san-pickleball-alp-4-1760302356.webp', 'owner1@fieldmate.local', CURRENT_TIMESTAMP - INTERVAL '145 days'),
        ('Sân Pickleball Văn Thánh', '48/10 Điện Biên Phủ, Phường Thạnh Mỹ Tây, Thành phố Hồ Chí Minh', 10.7984000::NUMERIC, 106.7145000::NUMERIC, 'https://shopvnb.com/uploads/tin_tuc/san-pickleball-van-thanh-2_1779153439.webp', 'https://cdn.shopvnb.com/uploads/images/bai_viet/san-pickleball-van-thanh-4-1779153442.webp', 'owner1@fieldmate.local', CURRENT_TIMESTAMP - INTERVAL '140 days'),
        ('Sân Pickleball Vạn Phúc City', '140 Đường 16, Khu đô thị Vạn Phúc, Phường Hiệp Bình, Thành phố Hồ Chí Minh', 10.8416000::NUMERIC, 106.7341000::NUMERIC, 'https://shopvnb.com/uploads/tin_tuc/san-pickleball-van-phuc-city-2_1759952280.jpg', 'https://cdn.shopvnb.com/uploads/images/bai_viet/san-pickleball-van-phuc-city-4-1759952316.jpg', 'owner2@fieldmate.local', CURRENT_TIMESTAMP - INTERVAL '135 days'),
        ('Sân Pickleball Miss Ú', '14/3 Minh Phụng, Phường Đông Hưng Thuận, Thành phố Hồ Chí Minh', 10.8305000::NUMERIC, 106.6228000::NUMERIC, 'https://shopvnb.com/uploads/tin_tuc/san-pickleball-miss-u-1_1760141164.jpg', 'https://cdn.shopvnb.com/uploads/images/bai_viet/san-pickleball-miss-u-4-1760141091.webp', 'owner2@fieldmate.local', CURRENT_TIMESTAMP - INTERVAL '130 days'),
        ('Sân Pickleball 110 Đào Sư Tích', '110 Đào Sư Tích, Xã Nhà Bè, Thành phố Hồ Chí Minh', 10.7118000::NUMERIC, 106.7045000::NUMERIC, 'https://shopvnb.com/uploads/tin_tuc/san-pickleball-110-dao-su-tich-1_1761602127.jpg', 'https://cdn.shopvnb.com/uploads/images/bai_viet/san-pickleball-110-dao-su-tich-4-1761602128.webp', 'owner2@fieldmate.local', CURRENT_TIMESTAMP - INTERVAL '125 days'),
        ('Pickleball Club 21', '103 Dương Quảng Hàm, Phường An Nhơn, Thành phố Hồ Chí Minh', 10.8382000::NUMERIC, 106.6697000::NUMERIC, 'https://shopvnb.com/uploads/tin_tuc/san-pickleball-club-21-ho-chi-minh-5_1776135682.webp', 'https://cdn.shopvnb.com/uploads/images/bai_viet/san-pickleball-club-21-ho-chi-minh-4-1776135684.webp', 'owner3@fieldmate.local', CURRENT_TIMESTAMP - INTERVAL '120 days'),
        ('Pickle Dink Hồ Chí Minh', '36B/31 Đường B7, Làng Đại học Khu B, Xã Nhà Bè, Thành phố Hồ Chí Minh', 10.7129000::NUMERIC, 106.7032000::NUMERIC, 'https://shopvnb.com/uploads/tin_tuc/san-pickleball-pickle-dink-ho-chi-minh-1_1777337429.webp', 'https://cdn.shopvnb.com/uploads/images/bai_viet/san-pickleball-pickle-dink-ho-chi-minh-4-1777337716.jpg', 'owner3@fieldmate.local', CURRENT_TIMESTAMP - INTERVAL '115 days'),
        ('Pickleball Trung tâm Văn hóa Thể thao Quận 7', '1521 Huỳnh Tấn Phát, Phường Phú Thuận, Thành phố Hồ Chí Minh', 10.7283000::NUMERIC, 106.7212000::NUMERIC, 'https://shopvnb.com/uploads/images/san-pickleball-trung-tam-van-hoa-the-thao-quan-7.jpg', 'https://cdn.shopvnb.com/uploads/images/bai_viet/san-pickleball-trung-tam-van-hoa-the-thao-quan-7-4-1733879333.webp', 'owner3@fieldmate.local', CURRENT_TIMESTAMP - INTERVAL '110 days'),
        ('Sân Pickleball Unity', '136 Dương Đình Hội, Phường Phước Long, Thành phố Hồ Chí Minh', 10.8268000::NUMERIC, 106.7745000::NUMERIC, 'https://shopvnb.com/uploads/tin_tuc/san-pickleball-unity-4_1761678176.jpg', 'https://cdn.shopvnb.com/uploads/images/bai_viet/san-pickleball-the-kitchen-zone-4-1731091986.webp', 'owner4@fieldmate.local', CURRENT_TIMESTAMP - INTERVAL '105 days'),
        ('Sân Pickleball Banger', '90 Song Hành, Phường Bình Trưng, Thành phố Hồ Chí Minh', 10.7858000::NUMERIC, 106.7594000::NUMERIC, 'https://shopvnb.com/uploads/tin_tuc/san-pickleball-banger-8_1761687399.webp', 'https://cdn.shopvnb.com/uploads/images/bai_viet/san-pickleball-banger-4-1761687400.webp', 'owner4@fieldmate.local', CURRENT_TIMESTAMP - INTERVAL '100 days'),
        ('Sân Pickleball SACA', 'Đường 410, Phường Phước Long, Thành phố Hồ Chí Minh', 10.8217000::NUMERIC, 106.7769000::NUMERIC, 'https://shopvnb.com/uploads/tin_tuc/san-pickleball-saca-3_1760489883.jpg', 'https://cdn.shopvnb.com/uploads/images/bai_viet/san-pickleball-saca-4-1760489883.webp', 'owner4@fieldmate.local', CURRENT_TIMESTAMP - INTERVAL '95 days'),
        ('Pickleball Game On', '387 Lương Thế Vinh, Trung Văn, Nam Từ Liêm, Hà Nội', 20.9954035::NUMERIC, 105.7890950::NUMERIC, 'https://images.unsplash.com/photo-1626224583764-f87db24ac4ea', 'https://robohash.org/fieldmate-game-on-venue-logo.png', 'owner5@fieldmate.local', CURRENT_TIMESTAMP - INTERVAL '90 days'),
        ('Sân Pickleball Cổng B Ga Hà Nội', '1 Trần Quý Cáp, Văn Chương, Văn Miếu - Quốc Tử Giám, Hà Nội', 21.0268848::NUMERIC, 105.8407023::NUMERIC, 'https://images.unsplash.com/photo-1622163642998-1ea32b0bbc67', 'https://robohash.org/fieldmate-cong-b-ga-ha-noi-logo.png', 'owner5@fieldmate.local', CURRENT_TIMESTAMP - INTERVAL '85 days'),
        ('PAPI Sport Club', '67 Duy Tân, Phường Hòa Cường, Thành phố Đà Nẵng', 16.0486161::NUMERIC, 108.2109835::NUMERIC, 'https://cdn.shopvnb.com/uploads/images/bai_viet/san-papi-pickleball-1-1776287904.webp', 'https://cdn.shopvnb.com/uploads/images/bai_viet/san-papi-pickleball-2-1776288940.jpg', 'owner6@fieldmate.local', CURRENT_TIMESTAMP - INTERVAL '80 days'),
        ('Sông Thu Pickleball', '36D Dương Đình Nghệ, Phường An Hải, Thành phố Đà Nẵng', 16.0688731::NUMERIC, 108.2390624::NUMERIC, 'https://cdn.shopvnb.com/uploads/images/bai_viet/san-pickleball-song-thu-1-1776021730.jpg', 'https://cdn.shopvnb.com/uploads/images/bai_viet/san-pickleball-song-thu-4-1776021730.jpg', 'owner6@fieldmate.local', CURRENT_TIMESTAMP - INTERVAL '75 days'),
        ('Say Hi Pickleball Cồn Khương', '37 Nguyễn Văn Cừ, Phường Cái Khế, Thành phố Cần Thơ', 10.0582957::NUMERIC, 105.7801687::NUMERIC, 'https://images.unsplash.com/photo-1599474924187-334a4ae5bd3c', 'https://robohash.org/fieldmate-con-khuong-venue-logo.png', 'owner7@fieldmate.local', CURRENT_TIMESTAMP - INTERVAL '70 days'),
        ('Bee Pickleball Cần Thơ', '11 Đường Phạm Công Trứ, Cồn Khương, Phường Cái Khế, Thành phố Cần Thơ', 10.0600911::NUMERIC, 105.7812480::NUMERIC, 'https://cdn.shopvnb.com/uploads/images/bai_viet/bee-pickleball-can-tho-1-1760644891.jpg', 'https://cdn.shopvnb.com/uploads/images/bai_viet/bee-pickleball-can-tho-2-1760644891.jpg', 'owner7@fieldmate.local', CURRENT_TIMESTAMP - INTERVAL '65 days')
) AS seed(name, address, latitude, longitude, banner, logo, owner_email, created_at)
JOIN users owner ON owner.email = seed.owner_email;

INSERT INTO benefits (venue_id, name)
SELECT venue.id, benefit.name
FROM venues venue
CROSS JOIN (
    VALUES
        ('Bãi giữ xe'),
        ('Phòng thay đồ'),
        ('Nhà vệ sinh'),
        ('Nước uống'),
        ('Hệ thống đèn chiếu sáng')
) AS benefit(name);

INSERT INTO rules (venue_id, name)
SELECT venue.id, venue_rule.name
FROM venues venue
CROSS JOIN (
    VALUES
        ('Khách hàng phải đến đúng giờ đã đặt'),
        ('Không mang giày đinh sắt vào sân'),
        ('Không hút thuốc trong khu vực sân'),
        ('Giữ gìn vệ sinh chung'),
        ('Phải kết thúc đúng thời gian đã đặt')
) AS venue_rule(name);

INSERT INTO venue_images (venue_id, url)
SELECT venue.id, image.url
FROM (
    VALUES
        ('Sân Pickleball VNA', 'https://cdn.shopvnb.com/uploads/images/bai_viet/san-pickleball-vna-1-1731721604.webp'),
        ('Sân Pickleball VNA', 'https://cdn.shopvnb.com/uploads/images/bai_viet/san-pickleball-vna-4-1731721606.webp'),
        ('Sân Pickleball VNA', 'https://cdn.shopvnb.com/uploads/images/tin_tuc/san-pickleball-rudal-1-1720646249.webp'),
        ('Sân Pickleball VNA', 'https://cdn.shopvnb.com/uploads/images/tin_tuc/san-pickleball-rudal-2-1720646249.webp'),
        ('Sân Pickleball ALP', 'https://cdn.shopvnb.com/uploads/images/bai_viet/san-pickleball-alp-1-1760302439.jpg'),
        ('Sân Pickleball ALP', 'https://cdn.shopvnb.com/uploads/images/bai_viet/san-pickleball-alp-3-1760302439.jpg'),
        ('Sân Pickleball ALP', 'https://cdn.shopvnb.com/uploads/images/bai_viet/pickleball-168-nguyen-huu-dat-1-1761676713.webp'),
        ('Sân Pickleball ALP', 'https://cdn.shopvnb.com/uploads/images/bai_viet/pickleball-168-nguyen-huu-dat-2-1761676714.webp'),
        ('Sân Pickleball Văn Thánh', 'https://cdn.shopvnb.com/uploads/images/bai_viet/san-pickleball-van-thanh-1-1779153440.webp'),
        ('Sân Pickleball Văn Thánh', 'https://cdn.shopvnb.com/uploads/images/bai_viet/san-pickleball-van-thanh-3-1779153441.webp'),
        ('Sân Pickleball Văn Thánh', 'https://cdn.shopvnb.com/uploads/images/bai_viet/san-pickleball-poc-1-1730671186.webp'),
        ('Sân Pickleball Văn Thánh', 'https://cdn.shopvnb.com/uploads/images/bai_viet/san-pickleball-poc-2-1730671187.webp'),
        ('Sân Pickleball Vạn Phúc City', 'https://cdn.shopvnb.com/uploads/images/bai_viet/san-pickleball-van-phuc-city-1-1759952316.jpg'),
        ('Sân Pickleball Vạn Phúc City', 'https://cdn.shopvnb.com/uploads/images/bai_viet/san-pickleball-van-phuc-city-3-1759951821.webp'),
        ('Sân Pickleball Vạn Phúc City', 'https://cdn.shopvnb.com/uploads/images/tin_tuc/san-pickleball-thanh-thai-1-1721268349.webp'),
        ('Sân Pickleball Vạn Phúc City', 'https://cdn.shopvnb.com/uploads/images/tin_tuc/san-pickleball-thanh-thai-2-1721268349.webp'),
        ('Sân Pickleball Miss Ú', 'https://cdn.shopvnb.com/uploads/images/bai_viet/san-pickleball-miss-u-2-1760141164.jpg'),
        ('Sân Pickleball Miss Ú', 'https://cdn.shopvnb.com/uploads/images/bai_viet/san-pickleball-miss-u-3-1760141164.jpg'),
        ('Sân Pickleball Miss Ú', 'https://n7media.coolmate.me/image/June2025/review-top-san-pickleball-phu-nhuan-ban-nhat-dinh-phai-thu-2.jpg'),
        ('Sân Pickleball Miss Ú', 'https://n7media.coolmate.me/image/June2025/review-top-san-pickleball-phu-nhuan-ban-nhat-dinh-phai-thu-3.jpg'),
        ('Sân Pickleball 110 Đào Sư Tích', 'https://cdn.shopvnb.com/uploads/images/bai_viet/san-pickleball-110-dao-su-tich-2-1761602150.jpg'),
        ('Sân Pickleball 110 Đào Sư Tích', 'https://cdn.shopvnb.com/uploads/images/bai_viet/san-pickleball-110-dao-su-tich-3-1761602127.webp'),
        ('Sân Pickleball 110 Đào Sư Tích', 'https://cdn.shopvnb.com/uploads/images/bai_viet/san-pickleball-an-phu-3-1724469300.webp'),
        ('Sân Pickleball 110 Đào Sư Tích', 'https://cdn.shopvnb.com/uploads/images/bai_viet/san-pickleball-an-phu-4-1724469301.webp'),
        ('Pickleball Club 21', 'https://cdn.shopvnb.com/uploads/images/bai_viet/san-pickleball-club-21-ho-chi-minh-1-1776135682.webp'),
        ('Pickleball Club 21', 'https://cdn.shopvnb.com/uploads/images/bai_viet/san-pickleball-club-21-ho-chi-minh-2-1776135683.webp'),
        ('Pickleball Club 21', 'https://cdn.shopvnb.com/uploads/images/bai_viet/san-pickleball-club-21-ho-chi-minh-3-1776135684.webp'),
        ('Pickleball Club 21', 'https://cdn.shopvnb.com/uploads/images/tin_tuc/san-pickleball-vuon-lan-1-1721617148.webp'),
        ('Pickle Dink Hồ Chí Minh', 'https://cdn.shopvnb.com/uploads/images/bai_viet/san-pickleball-pickle-dink-ho-chi-minh-2-1777337430.webp'),
        ('Pickle Dink Hồ Chí Minh', 'https://cdn.shopvnb.com/uploads/images/bai_viet/san-pickleball-pickle-dink-ho-chi-minh-3-1777337431.webp'),
        ('Pickle Dink Hồ Chí Minh', 'https://cdn.shopvnb.com/uploads/images/tin_tuc/san-pickleball-vuon-lan-2-1721617148.webp'),
        ('Pickle Dink Hồ Chí Minh', 'https://cdn.shopvnb.com/uploads/images/tin_tuc/san-pickleball-vuon-lan-3-1721617149.webp'),
        ('Pickleball Trung tâm Văn hóa Thể thao Quận 7', 'https://cdn.shopvnb.com/uploads/images/bai_viet/san-pickleball-trung-tam-van-hoa-the-thao-quan-7-1-1733879331.webp'),
        ('Pickleball Trung tâm Văn hóa Thể thao Quận 7', 'https://cdn.shopvnb.com/uploads/images/bai_viet/san-pickleball-trung-tam-van-hoa-the-thao-quan-7-2-1733879332.webp'),
        ('Pickleball Trung tâm Văn hóa Thể thao Quận 7', 'https://cdn.shopvnb.com/uploads/images/bai_viet/san-pickleball-trung-tam-van-hoa-the-thao-quan-7-3-1733879333.webp'),
        ('Pickleball Trung tâm Văn hóa Thể thao Quận 7', 'https://cdn.shopvnb.com/uploads/images/tin_tuc/san-pickleball-102-1-1721438741.webp'),
        ('Sân Pickleball Unity', 'https://cdn.shopvnb.com/uploads/images/bai_viet/san-pickleball-unity-1-1761678199.jpg'),
        ('Sân Pickleball Unity', 'https://cdn.shopvnb.com/uploads/images/bai_viet/san-pickleball-unity-2-1761678199.jpg'),
        ('Sân Pickleball Unity', 'https://cdn.shopvnb.com/uploads/images/bai_viet/san-pickleball-unity-3-1761678199.jpg'),
        ('Sân Pickleball Unity', 'https://cdn.shopvnb.com/uploads/images/tin_tuc/san-pickleball-102-2-1721438741.webp'),
        ('Sân Pickleball Banger', 'https://cdn.shopvnb.com/uploads/images/bai_viet/san-pickleball-banger-1-1761687419.jpg'),
        ('Sân Pickleball Banger', 'https://cdn.shopvnb.com/uploads/images/bai_viet/san-pickleball-banger-2-1761687419.jpg'),
        ('Sân Pickleball Banger', 'https://cdn.shopvnb.com/uploads/images/tin_tuc/san-pickleball-130-che-lan-vien-1-1722039723.webp'),
        ('Sân Pickleball Banger', 'https://cdn.shopvnb.com/uploads/images/tin_tuc/san-pickleball-130-che-lan-vien-2-1722039724.webp'),
        ('Sân Pickleball SACA', 'https://cdn.shopvnb.com/uploads/images/bai_viet/san-pickleball-saca-1-1760490524.jpg'),
        ('Sân Pickleball SACA', 'https://cdn.shopvnb.com/uploads/images/bai_viet/san-pickleball-saca-2-1760490524.jpg'),
        ('Sân Pickleball SACA', 'https://cdn.shopvnb.com/uploads/images/san-pickleball-002-7.webp'),
        ('Sân Pickleball SACA', 'https://cdn.shopvnb.com/uploads/images/tin_tuc/san-pickleball-002-2-1720831936.webp'),
        ('Pickleball Game On', 'https://cdn.shopvnb.com/uploads/images/bai_viet/san-pickleball-game-on-1-1762114048.webp'),
        ('Pickleball Game On', 'https://cdn.shopvnb.com/uploads/images/bai_viet/san-pickleball-game-on-2-1762114050.webp'),
        ('Pickleball Game On', 'https://cdn.shopvnb.com/uploads/images/bai_viet/san-pickleball-game-on-3-1762114819.webp'),
        ('Pickleball Game On', 'https://cdn.shopvnb.com/uploads/images/bai_viet/san-pickleball-game-on-4-1762114821.webp'),
        ('Sân Pickleball Cổng B Ga Hà Nội', 'https://cdn.shopvnb.com/uploads/images/bai_viet/san-pickleball-cong-b-ga-ha-noi-1-1776974416.jpg'),
        ('Sân Pickleball Cổng B Ga Hà Nội', 'https://cdn.shopvnb.com/uploads/images/bai_viet/san-pickleball-cong-b-ga-ha-noi-2-1776971518.webp'),
        ('Sân Pickleball Cổng B Ga Hà Nội', 'https://cdn.shopvnb.com/uploads/images/bai_viet/san-pickleball-cong-b-ga-ha-noi-3-1776971519.webp'),
        ('Sân Pickleball Cổng B Ga Hà Nội', 'https://cdn.shopvnb.com/uploads/images/bai_viet/san-pickleball-cong-b-ga-ha-noi-4-1776971520.webp'),
        ('PAPI Sport Club', 'https://cdn.shopvnb.com/uploads/images/bai_viet/san-papi-pickleball-3-1776287905.webp'),
        ('PAPI Sport Club', 'https://cdn.shopvnb.com/uploads/images/bai_viet/san-papi-pickleball-4-1776287905.webp'),
        ('PAPI Sport Club', 'https://cdn.shopvnb.com/uploads/images/bai_viet/san-papi-pickleball-5-1776287905.webp'),
        ('PAPI Sport Club', 'https://cdn.shopvnb.com/uploads/images/bai_viet/san-papi-pickleball-6-1776287906.webp'),
        ('Sông Thu Pickleball', 'https://cdn.shopvnb.com/uploads/images/bai_viet/san-pickleball-song-thu-2-1776021613.webp'),
        ('Sông Thu Pickleball', 'https://cdn.shopvnb.com/uploads/images/bai_viet/san-pickleball-song-thu-3-1776021614.webp'),
        ('Sông Thu Pickleball', 'https://cdn.shopvnb.com/uploads/images/bai_viet/san-pickleball-song-thu-5-1776021615.webp'),
        ('Sông Thu Pickleball', 'https://cdn.shopvnb.com/uploads/images/bai_viet/san-pickleball-song-thu-6-1776021615.webp'),
        ('Say Hi Pickleball Cồn Khương', 'https://cdn.shopvnb.com/uploads/images/bai_viet/san-pickleball-con-khuong-1-1776740058.webp'),
        ('Say Hi Pickleball Cồn Khương', 'https://cdn.shopvnb.com/uploads/images/bai_viet/san-pickleball-con-khuong-2-1776740059.webp'),
        ('Say Hi Pickleball Cồn Khương', 'https://cdn.shopvnb.com/uploads/images/bai_viet/san-pickleball-con-khuong-3-1776740060.webp'),
        ('Say Hi Pickleball Cồn Khương', 'https://cdn.shopvnb.com/uploads/images/bai_viet/san-pickleball-con-khuong-4-1776740060.webp'),
        ('Bee Pickleball Cần Thơ', 'https://cdn.shopvnb.com/uploads/images/bai_viet/bee-pickleball-can-tho-3-1760644891.jpg'),
        ('Bee Pickleball Cần Thơ', 'https://cdn.shopvnb.com/uploads/images/bai_viet/bee-pickleball-can-tho-4-1760644866.webp'),
        ('Bee Pickleball Cần Thơ', 'https://cdn.shopvnb.com/uploads/images/bai_viet/bee-pickleball-can-tho-5-1760644866.webp'),
        ('Bee Pickleball Cần Thơ', 'https://cdn.shopvnb.com/uploads/images/bai_viet/bee-pickleball-can-tho-6-1760644867.webp')
) AS image(venue_name, url)
JOIN venues venue ON venue.name = image.venue_name;

WITH venue_sports(venue_name, sports, base_price) AS (
    VALUES
        ('Sân Pickleball VNA', ARRAY['Pickleball', 'Cầu lông', 'Tennis', 'Bóng rổ'], 100000.00::NUMERIC),
        ('Sân Pickleball ALP', ARRAY['Pickleball', 'Bóng đá', 'Cầu lông', 'Bóng chuyền'], 110000.00::NUMERIC),
        ('Sân Pickleball Văn Thánh', ARRAY['Pickleball', 'Tennis', 'Bóng rổ', 'Bóng chuyền'], 120000.00::NUMERIC),
        ('Sân Pickleball Vạn Phúc City', ARRAY['Bóng đá', 'Cầu lông', 'Pickleball', 'Tennis'], 130000.00::NUMERIC),
        ('Sân Pickleball Miss Ú', ARRAY['Cầu lông', 'Pickleball', 'Bóng rổ', 'Bóng chuyền'], 90000.00::NUMERIC),
        ('Sân Pickleball 110 Đào Sư Tích', ARRAY['Bóng đá', 'Pickleball', 'Tennis', 'Bóng chuyền'], 140000.00::NUMERIC),
        ('Pickleball Club 21', ARRAY['Pickleball', 'Cầu lông', 'Bóng rổ', 'Tennis'], 120000.00::NUMERIC),
        ('Pickle Dink Hồ Chí Minh', ARRAY['Bóng đá', 'Cầu lông', 'Pickleball', 'Bóng chuyền'], 150000.00::NUMERIC),
        ('Pickleball Trung tâm Văn hóa Thể thao Quận 7', ARRAY['Pickleball', 'Tennis', 'Bóng rổ', 'Bóng chuyền'], 100000.00::NUMERIC),
        ('Sân Pickleball Unity', ARRAY['Bóng đá', 'Cầu lông', 'Pickleball', 'Tennis'], 160000.00::NUMERIC),
        ('Sân Pickleball Banger', ARRAY['Cầu lông', 'Pickleball', 'Bóng rổ', 'Bóng chuyền'], 110000.00::NUMERIC),
        ('Sân Pickleball SACA', ARRAY['Bóng đá', 'Pickleball', 'Tennis', 'Bóng chuyền'], 130000.00::NUMERIC),
        ('Pickleball Game On', ARRAY['Pickleball', 'Pickleball', 'Pickleball', 'Pickleball'], 140000.00::NUMERIC),
        ('Sân Pickleball Cổng B Ga Hà Nội', ARRAY['Pickleball', 'Pickleball', 'Pickleball', 'Pickleball'], 140000.00::NUMERIC),
        ('PAPI Sport Club', ARRAY['Pickleball', 'Pickleball', 'Pickleball', 'Pickleball'], 110000.00::NUMERIC),
        ('Sông Thu Pickleball', ARRAY['Pickleball', 'Pickleball', 'Pickleball', 'Pickleball'], 90000.00::NUMERIC),
        ('Say Hi Pickleball Cồn Khương', ARRAY['Pickleball', 'Pickleball', 'Pickleball', 'Pickleball'], 40000.00::NUMERIC),
        ('Bee Pickleball Cần Thơ', ARRAY['Pickleball', 'Pickleball', 'Pickleball', 'Pickleball'], 70000.00::NUMERIC)
)
INSERT INTO courts (
    name, price_per_hour, status, venue_id, sport_type_id, created_at, updated_at
)
SELECT
    sport.name || ' ' || court_number,
    venue_sports.base_price + (court_number * 10000.00),
    'ACTIVE',
    venue.id,
    sport.id,
    venue.created_at + INTERVAL '1 day',
    venue.created_at + INTERVAL '1 day'
FROM venue_sports
JOIN venues venue ON venue.name = venue_sports.venue_name
CROSS JOIN GENERATE_SERIES(1, 4) AS generated_court(court_number)
JOIN sport_types sport ON sport.name = venue_sports.sports[court_number];

INSERT INTO owner_payment_accounts (
    owner_id, provider, status, created_at, updated_at
)
SELECT owner.id, provider.name, 'ACTIVE',
       CURRENT_TIMESTAMP - INTERVAL '60 days',
       CURRENT_TIMESTAMP - INTERVAL '60 days'
FROM users owner
CROSS JOIN (VALUES ('MOMO'), ('VNPAY')) AS provider(name)
WHERE owner.role = 'COURT_OWNER';

INSERT INTO momo_credentials (
    payment_account_id, partner_code, access_key, secret_key, created_at, updated_at
)
SELECT account.id, seed.partner_code, seed.access_key, seed.secret_key,
       account.created_at, account.created_at
FROM (
    VALUES
        ('owner1@fieldmate.local', '  MOMO', 'v1:34odNprMN9x4Kwr799irAP0Ap8IxhW5bubZT5jRUmlSoBa7/F4D2hEw=', 'v1:a7Z7lrp1Y1jt7wIjUunrdrcCY6nThM5osjOgdRm92kcE64Omv7RYyhkcyW5cASOe0EeLIO+yN8xiaey1'),
        ('owner2@fieldmate.local', ' MOMO', 'v1:34odNprMN9x4Kwr799irAP0Ap8IxhW5bubZT5jRUmlSoBa7/F4D2hEw=', 'v1:a7Z7lrp1Y1jt7wIjUunrdrcCY6nThM5osjOgdRm92kcE64Omv7RYyhkcyW5cASOe0EeLIO+yN8xiaey1'),
        ('owner3@fieldmate.local', 'MOMO ', 'v1:34odNprMN9x4Kwr799irAP0Ap8IxhW5bubZT5jRUmlSoBa7/F4D2hEw=', 'v1:a7Z7lrp1Y1jt7wIjUunrdrcCY6nThM5osjOgdRm92kcE64Omv7RYyhkcyW5cASOe0EeLIO+yN8xiaey1'),
        ('owner4@fieldmate.local', ' MOMO ', 'v1:34odNprMN9x4Kwr799irAP0Ap8IxhW5bubZT5jRUmlSoBa7/F4D2hEw=', 'v1:a7Z7lrp1Y1jt7wIjUunrdrcCY6nThM5osjOgdRm92kcE64Omv7RYyhkcyW5cASOe0EeLIO+yN8xiaey1'),
        ('owner5@fieldmate.local', 'MOMO  ', 'v1:34odNprMN9x4Kwr799irAP0Ap8IxhW5bubZT5jRUmlSoBa7/F4D2hEw=', 'v1:a7Z7lrp1Y1jt7wIjUunrdrcCY6nThM5osjOgdRm92kcE64Omv7RYyhkcyW5cASOe0EeLIO+yN8xiaey1'),
        ('owner6@fieldmate.local', '   MOMO', 'v1:34odNprMN9x4Kwr799irAP0Ap8IxhW5bubZT5jRUmlSoBa7/F4D2hEw=', 'v1:a7Z7lrp1Y1jt7wIjUunrdrcCY6nThM5osjOgdRm92kcE64Omv7RYyhkcyW5cASOe0EeLIO+yN8xiaey1'),
        ('owner7@fieldmate.local', 'MOMO   ', 'v1:34odNprMN9x4Kwr799irAP0Ap8IxhW5bubZT5jRUmlSoBa7/F4D2hEw=', 'v1:a7Z7lrp1Y1jt7wIjUunrdrcCY6nThM5osjOgdRm92kcE64Omv7RYyhkcyW5cASOe0EeLIO+yN8xiaey1')
) AS seed(owner_email, partner_code, access_key, secret_key)
JOIN users owner ON owner.email = seed.owner_email
JOIN owner_payment_accounts account
  ON account.owner_id = owner.id AND account.provider = 'MOMO';

INSERT INTO vnpay_credentials (
    payment_account_id, tmn_code, hash_secret, created_at, updated_at
)
SELECT account.id, seed.tmn_code, seed.hash_secret,
       account.created_at, account.created_at
FROM (
    VALUES
        ('owner1@fieldmate.local', '   ZTAY1P26  ', 'v1:SSC+6fi7azFrPHs6DB3cftHUk0IRiXglCvmGPPIzyWzdThJg3GMIG8HGOFbrgPG/4cUjUnQ81HvIhYiS'),
        ('owner2@fieldmate.local', ' ZTAY1P26     ', 'v1:SSC+6fi7azFrPHs6DB3cftHUk0IRiXglCvmGPPIzyWzdThJg3GMIG8HGOFbrgPG/4cUjUnQ81HvIhYiS'),
        ('owner3@fieldmate.local', 'ZTAY1P26  ', 'v1:SSC+6fi7azFrPHs6DB3cftHUk0IRiXglCvmGPPIzyWzdThJg3GMIG8HGOFbrgPG/4cUjUnQ81HvIhYiS'),
        ('owner4@fieldmate.local', 'ZTAY1P26 ', 'v1:SSC+6fi7azFrPHs6DB3cftHUk0IRiXglCvmGPPIzyWzdThJg3GMIG8HGOFbrgPG/4cUjUnQ81HvIhYiS'),
        ('owner5@fieldmate.local', '  ZTAY1P26   ', 'v1:SSC+6fi7azFrPHs6DB3cftHUk0IRiXglCvmGPPIzyWzdThJg3GMIG8HGOFbrgPG/4cUjUnQ81HvIhYiS'),
        ('owner6@fieldmate.local', '    ZTAY1P26 ', 'v1:SSC+6fi7azFrPHs6DB3cftHUk0IRiXglCvmGPPIzyWzdThJg3GMIG8HGOFbrgPG/4cUjUnQ81HvIhYiS'),
        ('owner7@fieldmate.local', ' ZTAY1P26  ', 'v1:SSC+6fi7azFrPHs6DB3cftHUk0IRiXglCvmGPPIzyWzdThJg3GMIG8HGOFbrgPG/4cUjUnQ81HvIhYiS')
) AS seed(owner_email, tmn_code, hash_secret)
JOIN users owner ON owner.email = seed.owner_email
JOIN owner_payment_accounts account
  ON account.owner_id = owner.id AND account.provider = 'VNPAY';

WITH booking_seed AS (
    SELECT
        court.id AS court_id,
        slot_number,
        CASE slot_number
            WHEN 1 THEN CURRENT_DATE - (30 + (court.id % 10))::INTEGER
            WHEN 2 THEN CURRENT_DATE - (5 + (court.id % 15))::INTEGER
            WHEN 3 THEN CURRENT_DATE + (1 + (court.id % 7))::INTEGER
            WHEN 4 THEN CURRENT_DATE + (8 + (court.id % 7))::INTEGER
            WHEN 5 THEN CURRENT_DATE + (15 + (court.id % 7))::INTEGER
        END AS booking_date,
        TIME '06:00' + (((court.id + slot_number) % 7) * INTERVAL '2 hours') AS start_time,
        CASE slot_number
            WHEN 1 THEN 'COMPLETED'
            WHEN 2 THEN 'EXPIRED'
            WHEN 3 THEN 'CONFIRMED'
            WHEN 4 THEN 'PENDING'
            WHEN 5 THEN 'CONFIRMED'
        END AS status,
        court.price_per_hour
    FROM courts court
    CROSS JOIN GENERATE_SERIES(1, 5) AS generated_booking(slot_number)
),
dated_seed AS (
    SELECT
        booking_seed.*,
        start_time + INTERVAL '90 minutes' AS end_time,
        CASE slot_number
            WHEN 1 THEN booking_date::TIMESTAMP - INTERVAL '2 days'
            WHEN 2 THEN booking_date::TIMESTAMP - INTERVAL '2 days'
            WHEN 3 THEN CURRENT_TIMESTAMP - INTERVAL '2 days'
            WHEN 4 THEN CURRENT_TIMESTAMP - INTERVAL '5 minutes'
            WHEN 5 THEN CURRENT_TIMESTAMP - INTERVAL '1 day'
        END AS created_at
    FROM booking_seed
)
INSERT INTO bookings (
    customer_id, court_id, booking_date, start_time, end_time,
    total_price, required_deposit, status, created_at, updated_at
)
SELECT
    customer.id,
    dated_seed.court_id,
    dated_seed.booking_date,
    dated_seed.start_time,
    dated_seed.end_time,
    ROUND(dated_seed.price_per_hour * 1.50, 2),
    ROUND(dated_seed.price_per_hour * 1.50 * 0.30, 2),
    dated_seed.status,
    dated_seed.created_at,
    CASE dated_seed.slot_number
        WHEN 1 THEN dated_seed.booking_date + dated_seed.end_time + INTERVAL '1 hour'
        WHEN 4 THEN dated_seed.created_at + INTERVAL '1 minute'
        ELSE dated_seed.created_at + INTERVAL '10 minutes'
    END
FROM dated_seed
JOIN users customer
  ON customer.email =
     'customer'
     || ((((dated_seed.court_id - 1) * 5 + dated_seed.slot_number - 1) % 10) + 1)::TEXT
     || '@fieldmate.local';

INSERT INTO payments (
    booking_id, payment_account_id, amount, payment_type, status,
    payment_method, transaction_code, paid_at, created_at, updated_at
)
SELECT
    booking.id,
    account.id,
    booking.required_deposit,
    'DEPOSIT',
    'PAID',
    'MOMO',
    'PAY_' || UPPER(REPLACE(GEN_RANDOM_UUID()::TEXT, '-', '')),
    booking.created_at + INTERVAL '5 minutes',
    booking.created_at,
    booking.created_at + INTERVAL '5 minutes'
FROM bookings booking
JOIN courts court ON court.id = booking.court_id
JOIN venues venue ON venue.id = court.venue_id
JOIN owner_payment_accounts account
  ON account.owner_id = venue.owner_id AND account.provider = 'MOMO'
WHERE booking.status = 'COMPLETED';

INSERT INTO payments (
    booking_id, payment_account_id, amount, payment_type, status,
    payment_method, transaction_code, paid_at, created_at, updated_at
)
SELECT
    booking.id,
    account.id,
    booking.total_price - booking.required_deposit,
    'REMAINING',
    'PAID',
    'VNPAY',
    'PAY_' || UPPER(REPLACE(GEN_RANDOM_UUID()::TEXT, '-', '')),
    booking.created_at + INTERVAL '15 minutes',
    booking.created_at + INTERVAL '10 minutes',
    booking.created_at + INTERVAL '15 minutes'
FROM bookings booking
JOIN courts court ON court.id = booking.court_id
JOIN venues venue ON venue.id = court.venue_id
JOIN owner_payment_accounts account
  ON account.owner_id = venue.owner_id AND account.provider = 'VNPAY'
WHERE booking.status = 'COMPLETED';

INSERT INTO payments (
    booking_id, payment_account_id, amount, payment_type, status,
    payment_method, transaction_code, paid_at, created_at, updated_at
)
SELECT
    booking.id,
    account.id,
    booking.required_deposit,
    'DEPOSIT',
    'PAID',
    account.provider,
    'PAY_' || UPPER(REPLACE(GEN_RANDOM_UUID()::TEXT, '-', '')),
    booking.created_at + INTERVAL '5 minutes',
    booking.created_at,
    booking.created_at + INTERVAL '5 minutes'
FROM bookings booking
JOIN courts court ON court.id = booking.court_id
JOIN venues venue ON venue.id = court.venue_id
JOIN owner_payment_accounts account
  ON account.owner_id = venue.owner_id
 AND account.provider = CASE WHEN booking.id % 2 = 0 THEN 'MOMO' ELSE 'VNPAY' END
WHERE booking.status = 'CONFIRMED';

INSERT INTO payments (
    booking_id, payment_account_id, amount, payment_type, status,
    payment_method, transaction_code, paid_at, created_at, updated_at
)
SELECT
    booking.id,
    account.id,
    booking.required_deposit,
    'DEPOSIT',
    booking.status,
    account.provider,
    'PAY_' || UPPER(REPLACE(GEN_RANDOM_UUID()::TEXT, '-', '')),
    NULL,
    booking.created_at,
    booking.created_at + INTERVAL '1 minute'
FROM bookings booking
JOIN courts court ON court.id = booking.court_id
JOIN venues venue ON venue.id = court.venue_id
JOIN owner_payment_accounts account
  ON account.owner_id = venue.owner_id
 AND account.provider = CASE WHEN booking.id % 2 = 0 THEN 'MOMO' ELSE 'VNPAY' END
WHERE booking.status IN ('PENDING', 'EXPIRED');

INSERT INTO hero_banners (url, target_url, created_at, updated_at) VALUES
    ('https://www.decathlon.vn/blog/wp-content/uploads/2024/08/dung-cu-choi-pickleball-e1722498065798.webp', 'https://www.decathlon.vn/blog/pickleball-la-gi/', CURRENT_TIMESTAMP - INTERVAL '30 days', CURRENT_TIMESTAMP - INTERVAL '30 days'),
    ('https://cdn.hstatic.net/files/1000341630/collection/cover_web_pc__3__dece928b9ff24b428f85852f5dec931a.png', 'https://kamito.vn/collections/pickleball', CURRENT_TIMESTAMP - INTERVAL '25 days', CURRENT_TIMESTAMP - INTERVAL '25 days'),
    ('https://mcdn.coolmate.me/image/November2023/mceclip0_46.jpg', 'https://www.coolmate.me/collection/do-the-thao-nam', CURRENT_TIMESTAMP - INTERVAL '20 days', CURRENT_TIMESTAMP - INTERVAL '20 days'),
    ('https://homepage.momocdn.net/img/momo-amazone-s3-api-241029082636-638657871963540172.jpg', 'https://www.momo.vn/', CURRENT_TIMESTAMP - INTERVAL '15 days', CURRENT_TIMESTAMP - INTERVAL '15 days'),
    ('https://vnpay.vn/s1/statics.vnpay.vn/2022/6/0t98r20u2ruh1654574469292.jpg', 'https://vnpay.vn/', CURRENT_TIMESTAMP - INTERVAL '10 days', CURRENT_TIMESTAMP - INTERVAL '10 days');

DO $$
DECLARE
    actual_count BIGINT;
BEGIN
    SELECT COUNT(*) INTO actual_count FROM users WHERE role = 'ADMIN';
    IF actual_count <> 1 THEN
        RAISE EXCEPTION 'Seed validation failed: expected 1 ADMIN, found %', actual_count;
    END IF;

    SELECT COUNT(*) INTO actual_count FROM users WHERE role = 'COURT_OWNER';
    IF actual_count <> 7 THEN
        RAISE EXCEPTION 'Seed validation failed: expected 7 COURT_OWNER users, found %', actual_count;
    END IF;

    SELECT COUNT(*) INTO actual_count FROM users WHERE role = 'CUSTOMER';
    IF actual_count <> 10 THEN
        RAISE EXCEPTION 'Seed validation failed: expected 10 CUSTOMER users, found %', actual_count;
    END IF;

    SELECT COUNT(*) INTO actual_count FROM users;
    IF actual_count <> 18 THEN
        RAISE EXCEPTION 'Seed validation failed: expected exactly 18 users, found %', actual_count;
    END IF;

    IF EXISTS (
        SELECT 1
        FROM users owner
        LEFT JOIN venues venue ON venue.owner_id = owner.id
        WHERE owner.role = 'COURT_OWNER'
        GROUP BY owner.id
        HAVING COUNT(venue.id) = 0 OR COUNT(venue.id) > 3
    ) THEN
        RAISE EXCEPTION 'Seed validation failed: every COURT_OWNER must own between 1 and 3 venues';
    END IF;

    SELECT COUNT(*) INTO actual_count FROM venues;
    IF actual_count <> 18 THEN
        RAISE EXCEPTION 'Seed validation failed: expected exactly 18 venues, found %', actual_count;
    END IF;

    IF EXISTS (
        SELECT 1
        FROM venues venue
        LEFT JOIN courts court ON court.venue_id = venue.id
        GROUP BY venue.id
        HAVING COUNT(court.id) <> 4
    ) THEN
        RAISE EXCEPTION 'Seed validation failed: every venue must have exactly 4 courts';
    END IF;

    SELECT COUNT(*) INTO actual_count FROM courts;
    IF actual_count <> 72 THEN
        RAISE EXCEPTION 'Seed validation failed: expected exactly 72 courts, found %', actual_count;
    END IF;

    IF EXISTS (
        SELECT 1
        FROM courts court
        LEFT JOIN bookings booking ON booking.court_id = court.id
        GROUP BY court.id
        HAVING COUNT(booking.id) < 5
    ) THEN
        RAISE EXCEPTION 'Seed validation failed: every court must have at least 5 bookings';
    END IF;

    SELECT COUNT(*) INTO actual_count FROM bookings;
    IF actual_count < 360 THEN
        RAISE EXCEPTION 'Seed validation failed: expected at least 360 bookings, found %', actual_count;
    END IF;

    IF EXISTS (
        SELECT 1
        FROM bookings booking
        JOIN users customer ON customer.id = booking.customer_id
        WHERE customer.role <> 'CUSTOMER'
    ) THEN
        RAISE EXCEPTION 'Seed validation failed: every booking must belong to a CUSTOMER';
    END IF;

    IF EXISTS (
        SELECT 1
        FROM bookings booking
        JOIN users customer ON customer.id = booking.customer_id
        WHERE customer.role = 'ADMIN'
    ) THEN
        RAISE EXCEPTION 'Seed validation failed: an ADMIN owns a booking';
    END IF;

    IF EXISTS (
        SELECT 1
        FROM bookings booking
        JOIN users customer ON customer.id = booking.customer_id
        WHERE customer.role = 'COURT_OWNER'
    ) THEN
        RAISE EXCEPTION 'Seed validation failed: a COURT_OWNER owns a booking';
    END IF;

    IF EXISTS (SELECT 1 FROM bookings WHERE start_time >= end_time) THEN
        RAISE EXCEPTION 'Seed validation failed: booking start_time must be before end_time';
    END IF;

    IF EXISTS (
        SELECT 1
        FROM bookings first_booking
        JOIN bookings second_booking
          ON first_booking.id < second_booking.id
         AND first_booking.court_id = second_booking.court_id
         AND first_booking.booking_date = second_booking.booking_date
         AND first_booking.start_time < second_booking.end_time
         AND first_booking.end_time > second_booking.start_time
        WHERE first_booking.status IN ('CONFIRMED', 'COMPLETED', 'PENDING')
          AND second_booking.status IN ('CONFIRMED', 'COMPLETED', 'PENDING')
          AND NOT (
              first_booking.status = 'PENDING'
              AND first_booking.created_at <= CURRENT_TIMESTAMP - INTERVAL '15 minutes'
          )
          AND NOT (
              second_booking.status = 'PENDING'
              AND second_booking.created_at <= CURRENT_TIMESTAMP - INTERVAL '15 minutes'
          )
    ) THEN
        RAISE EXCEPTION 'Seed validation failed: occupied bookings overlap';
    END IF;

    IF EXISTS (SELECT 1 FROM bookings WHERE total_price <= 0) THEN
        RAISE EXCEPTION 'Seed validation failed: booking total_price must be positive';
    END IF;

    IF EXISTS (
        SELECT 1 FROM bookings
        WHERE required_deposit <= 0 OR required_deposit > total_price
    ) THEN
        RAISE EXCEPTION 'Seed validation failed: invalid required_deposit';
    END IF;
END
$$;

DO $$
DECLARE
    actual_count BIGINT;
BEGIN
    IF EXISTS (
        SELECT 1
        FROM venues venue
        LEFT JOIN users owner ON owner.id = venue.owner_id
        WHERE owner.id IS NULL
        UNION ALL
        SELECT 1
        FROM courts court
        LEFT JOIN venues venue ON venue.id = court.venue_id
        LEFT JOIN sport_types sport ON sport.id = court.sport_type_id
        WHERE venue.id IS NULL OR sport.id IS NULL
        UNION ALL
        SELECT 1
        FROM bookings booking
        LEFT JOIN users customer ON customer.id = booking.customer_id
        LEFT JOIN courts court ON court.id = booking.court_id
        WHERE customer.id IS NULL OR court.id IS NULL
        UNION ALL
        SELECT 1
        FROM payments payment
        LEFT JOIN bookings booking ON booking.id = payment.booking_id
        LEFT JOIN owner_payment_accounts account ON account.id = payment.payment_account_id
        WHERE booking.id IS NULL
           OR (payment.payment_account_id IS NOT NULL AND account.id IS NULL)
    ) THEN
        RAISE EXCEPTION 'Seed validation failed: orphaned foreign key reference detected';
    END IF;

    IF EXISTS (
        SELECT transaction_code
        FROM payments
        WHERE transaction_code IS NOT NULL
        GROUP BY transaction_code
        HAVING COUNT(*) > 1
    ) THEN
        RAISE EXCEPTION 'Seed validation failed: duplicate payment transaction_code';
    END IF;

    IF EXISTS (
        SELECT 1
        FROM payments
        WHERE transaction_code IS NULL
           OR (payment_method IN ('MOMO', 'VNPAY') AND transaction_code !~ '^PAY_[0-9A-F]{32}$')
           OR (payment_method = 'CASH' AND transaction_code !~ '^CASH_[0-9A-F]{32}$')
    ) THEN
        RAISE EXCEPTION 'Seed validation failed: payment transaction_code format does not match backend generation';
    END IF;

    IF EXISTS (SELECT 1 FROM payments WHERE amount <= 0) THEN
        RAISE EXCEPTION 'Seed validation failed: payment amount must be positive';
    END IF;

    IF EXISTS (
        SELECT 1
        FROM owner_payment_accounts account
        JOIN users owner ON owner.id = account.owner_id
        WHERE owner.role <> 'COURT_OWNER'
    ) THEN
        RAISE EXCEPTION 'Seed validation failed: payment account owner is not COURT_OWNER';
    END IF;

    IF EXISTS (
        SELECT 1
        FROM payments payment
        JOIN bookings booking ON booking.id = payment.booking_id
        JOIN courts court ON court.id = booking.court_id
        JOIN venues venue ON venue.id = court.venue_id
        JOIN owner_payment_accounts account ON account.id = payment.payment_account_id
        WHERE account.owner_id <> venue.owner_id
    ) THEN
        RAISE EXCEPTION 'Seed validation failed: payment account does not belong to the venue owner';
    END IF;

    IF EXISTS (
        SELECT 1
        FROM payments payment
        JOIN owner_payment_accounts account ON account.id = payment.payment_account_id
        WHERE (payment.payment_method = 'MOMO' AND account.provider <> 'MOMO')
           OR (payment.payment_method = 'VNPAY' AND account.provider <> 'VNPAY')
           OR payment.payment_method = 'CASH'
    ) THEN
        RAISE EXCEPTION 'Seed validation failed: payment method and account provider do not match';
    END IF;

    SELECT COUNT(*) INTO actual_count FROM owner_payment_accounts;
    IF actual_count <> 14 THEN
        RAISE EXCEPTION 'Seed validation failed: expected 14 owner payment accounts, found %', actual_count;
    END IF;

    IF EXISTS (
        SELECT 1
        FROM users owner
        LEFT JOIN owner_payment_accounts account ON account.owner_id = owner.id
        WHERE owner.role = 'COURT_OWNER'
        GROUP BY owner.id
        HAVING COUNT(account.id) <> 2
           OR COUNT(account.id) FILTER (WHERE account.provider = 'MOMO') <> 1
           OR COUNT(account.id) FILTER (WHERE account.provider = 'VNPAY') <> 1
    ) THEN
        RAISE EXCEPTION 'Seed validation failed: each owner must have one MOMO and one VNPAY account';
    END IF;

    IF EXISTS (
        SELECT 1
        FROM momo_credentials credential
        JOIN owner_payment_accounts account ON account.id = credential.payment_account_id
        WHERE account.provider <> 'MOMO'
           OR credential.access_key !~ '^v1:[A-Za-z0-9+/]+={0,2}$'
           OR credential.secret_key !~ '^v1:[A-Za-z0-9+/]+={0,2}$'
        UNION ALL
        SELECT 1
        FROM vnpay_credentials credential
        JOIN owner_payment_accounts account ON account.id = credential.payment_account_id
        WHERE account.provider <> 'VNPAY'
           OR credential.hash_secret !~ '^v1:[A-Za-z0-9+/]+={0,2}$'
    ) THEN
        RAISE EXCEPTION 'Seed validation failed: invalid credential provider or ciphertext format';
    END IF;
END
$$;

DO $$
BEGIN
    IF EXISTS (
        WITH all_images(url) AS (
            SELECT avatar FROM users WHERE avatar IS NOT NULL
            UNION ALL
            SELECT logo FROM venues WHERE logo IS NOT NULL
            UNION ALL
            SELECT banner FROM venues WHERE banner IS NOT NULL
            UNION ALL
            SELECT url FROM venue_images
            UNION ALL
            SELECT url FROM hero_banners
        )
        SELECT 1
        FROM all_images
        GROUP BY LOWER(REGEXP_REPLACE(url, '\?.*$', ''))
        HAVING COUNT(*) > 1
    ) THEN
        RAISE EXCEPTION 'Seed validation failed: duplicate image URL detected';
    END IF;

    IF EXISTS (
        WITH all_images(url) AS (
            SELECT avatar FROM users WHERE avatar IS NOT NULL
            UNION ALL
            SELECT logo FROM venues WHERE logo IS NOT NULL
            UNION ALL
            SELECT banner FROM venues WHERE banner IS NOT NULL
            UNION ALL
            SELECT url FROM venue_images
            UNION ALL
            SELECT url FROM hero_banners
        )
        SELECT 1 FROM all_images WHERE url !~ '^https://[^[:space:]]+$'
    ) THEN
        RAISE EXCEPTION 'Seed validation failed: image URL must be an absolute HTTPS URL';
    END IF;

    IF EXISTS (
        SELECT LOWER(email)
        FROM users
        GROUP BY LOWER(email)
        HAVING COUNT(*) > 1
    ) THEN
        RAISE EXCEPTION 'Seed validation failed: duplicate email';
    END IF;

    IF EXISTS (
        SELECT phone_number
        FROM users
        WHERE phone_number IS NOT NULL
        GROUP BY phone_number
        HAVING COUNT(*) > 1
    ) THEN
        RAISE EXCEPTION 'Seed validation failed: duplicate phone number';
    END IF;

    IF EXISTS (
        SELECT 1 FROM users WHERE role NOT IN ('CUSTOMER', 'COURT_OWNER', 'ADMIN')
        UNION ALL
        SELECT 1 FROM venues WHERE status NOT IN ('ACTIVE', 'INACTIVE', 'PENDING', 'REJECTED')
        UNION ALL
        SELECT 1 FROM courts WHERE status NOT IN ('ACTIVE', 'INACTIVE', 'MAINTENANCE')
        UNION ALL
        SELECT 1 FROM bookings WHERE status NOT IN ('PENDING', 'CONFIRMED', 'COMPLETED', 'EXPIRED')
        UNION ALL
        SELECT 1 FROM owner_payment_accounts WHERE provider NOT IN ('MOMO', 'VNPAY')
        UNION ALL
        SELECT 1 FROM owner_payment_accounts WHERE status NOT IN ('PENDING', 'ACTIVE', 'INACTIVE', 'SUSPENDED')
        UNION ALL
        SELECT 1 FROM payments WHERE payment_type NOT IN ('DEPOSIT', 'REMAINING', 'FULL_PAYMENT')
        UNION ALL
        SELECT 1 FROM payments WHERE status NOT IN ('PENDING', 'PAID', 'FAILED', 'EXPIRED')
        UNION ALL
        SELECT 1 FROM payments WHERE payment_method NOT IN ('CASH', 'VNPAY', 'MOMO')
    ) THEN
        RAISE EXCEPTION 'Seed validation failed: invalid enum value';
    END IF;
END
$$;

DO $$
BEGIN
    IF EXISTS (
        SELECT 1
        FROM bookings booking
        JOIN courts court ON court.id = booking.court_id
        WHERE booking.total_price <> ROUND(
            court.price_per_hour
            * (EXTRACT(EPOCH FROM (booking.end_time - booking.start_time)) / 3600),
            2
        )
           OR booking.required_deposit <> ROUND(booking.total_price * 0.30, 2)
    ) THEN
        RAISE EXCEPTION 'Seed validation failed: booking price or 30 percent deposit is incorrect';
    END IF;

    IF EXISTS (
        SELECT 1
        FROM bookings booking
        LEFT JOIN payments payment
          ON payment.booking_id = booking.id AND payment.status = 'PAID'
        GROUP BY booking.id
        HAVING (booking.status = 'COMPLETED' AND COALESCE(SUM(payment.amount), 0) < booking.total_price)
            OR (booking.status = 'CONFIRMED' AND COALESCE(SUM(payment.amount), 0) < booking.required_deposit)
            OR (booking.status = 'PENDING' AND COALESCE(SUM(payment.amount), 0) >= booking.required_deposit)
    ) THEN
        RAISE EXCEPTION 'Seed validation failed: booking and paid amounts are inconsistent';
    END IF;

    IF EXISTS (
        SELECT 1
        FROM payments
        WHERE (status = 'PAID' AND paid_at IS NULL)
           OR (status IN ('PENDING', 'FAILED', 'EXPIRED') AND paid_at IS NOT NULL)
           OR updated_at < created_at
           OR (paid_at IS NOT NULL AND paid_at < created_at)
    ) THEN
        RAISE EXCEPTION 'Seed validation failed: payment status or timestamps are inconsistent';
    END IF;

    IF EXISTS (
        SELECT 1 FROM users WHERE updated_at < created_at
        UNION ALL
        SELECT 1 FROM venues WHERE updated_at < created_at
        UNION ALL
        SELECT 1 FROM courts WHERE updated_at < created_at
        UNION ALL
        SELECT 1 FROM bookings WHERE updated_at < created_at
        UNION ALL
        SELECT 1 FROM owner_payment_accounts WHERE updated_at < created_at
        UNION ALL
        SELECT 1 FROM momo_credentials WHERE updated_at < created_at
        UNION ALL
        SELECT 1 FROM vnpay_credentials WHERE updated_at < created_at
        UNION ALL
        SELECT 1 FROM hero_banners WHERE updated_at < created_at
    ) THEN
        RAISE EXCEPTION 'Seed validation failed: updated_at precedes created_at';
    END IF;

    IF EXISTS (
        SELECT 1
        FROM venues venue
        LEFT JOIN benefits benefit ON benefit.venue_id = venue.id
        GROUP BY venue.id
        HAVING COUNT(benefit.id) < 5
    ) THEN
        RAISE EXCEPTION 'Seed validation failed: every venue must have at least 5 benefits';
    END IF;

    IF EXISTS (
        SELECT 1
        FROM venues venue
        LEFT JOIN rules venue_rule ON venue_rule.venue_id = venue.id
        GROUP BY venue.id
        HAVING COUNT(venue_rule.id) < 5
    ) THEN
        RAISE EXCEPTION 'Seed validation failed: every venue must have at least 5 rules';
    END IF;

    IF EXISTS (
        SELECT 1
        FROM venues venue
        LEFT JOIN venue_images image ON image.venue_id = venue.id
        GROUP BY venue.id
        HAVING COUNT(image.id) <> 4
    ) THEN
        RAISE EXCEPTION 'Seed validation failed: every venue must have exactly 4 images';
    END IF;

    IF EXISTS (
        SELECT 1
        FROM venues venue
        JOIN users owner ON owner.id = venue.owner_id
        WHERE owner.role <> 'COURT_OWNER'
           OR venue.status <> 'ACTIVE'
           OR venue.latitude NOT BETWEEN -90 AND 90
           OR venue.longitude NOT BETWEEN -180 AND 180
    ) THEN
        RAISE EXCEPTION 'Seed validation failed: venue owner, status, or coordinates are invalid';
    END IF;

    IF EXISTS (
        SELECT 1
        FROM bookings booking
        JOIN courts court ON court.id = booking.court_id
        JOIN venues venue ON venue.id = court.venue_id
        WHERE court.status <> 'ACTIVE' OR venue.status <> 'ACTIVE'
    ) THEN
        RAISE EXCEPTION 'Seed validation failed: booking references an inactive court or venue';
    END IF;

    IF EXISTS (
        SELECT 1
        FROM users customer
        LEFT JOIN bookings booking ON booking.customer_id = customer.id
        WHERE customer.role = 'CUSTOMER'
        GROUP BY customer.id
        HAVING COUNT(booking.id) = 0
    ) THEN
        RAISE EXCEPTION 'Seed validation failed: booking distribution omitted a customer';
    END IF;
END
$$;
