CREATE TABLE IF NOT EXISTS users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email VARCHAR(100) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
    phone_number VARCHAR(20),
    first_name VARCHAR(50),
    last_name VARCHAR(50),
    avatar VARCHAR(500),
    role VARCHAR(20) NOT NULL,
    enabled BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP,
    CONSTRAINT ck_users_role
        CHECK (role IN ('CUSTOMER', 'COURT_OWNER', 'ADMIN'))
);

CREATE TABLE IF NOT EXISTS sport_types (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100) NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS venues (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(150) NOT NULL,
    address VARCHAR(255) NOT NULL,
    latitude NUMERIC(10, 7),
    longitude NUMERIC(10, 7),
    banner VARCHAR(500),
    logo VARCHAR(500),
    status VARCHAR(30) NOT NULL DEFAULT 'PENDING',
    owner_id BIGINT NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP,
    CONSTRAINT fk_venues_owner
        FOREIGN KEY (owner_id) REFERENCES users (id),
    CONSTRAINT ck_venues_status
        CHECK (status IN ('ACTIVE', 'INACTIVE', 'PENDING', 'REJECTED'))
);

CREATE TABLE IF NOT EXISTS benefits (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    venue_id BIGINT NOT NULL,
    CONSTRAINT fk_benefits_venue
        FOREIGN KEY (venue_id) REFERENCES venues (id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS rules (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    venue_id BIGINT NOT NULL,
    CONSTRAINT fk_rules_venue
        FOREIGN KEY (venue_id) REFERENCES venues (id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS venue_images (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    url VARCHAR(500) NOT NULL,
    venue_id BIGINT NOT NULL,
    CONSTRAINT fk_venue_images_venue
        FOREIGN KEY (venue_id) REFERENCES venues (id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS courts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    price_per_hour NUMERIC(12, 2) NOT NULL,
    status VARCHAR(30) NOT NULL DEFAULT 'ACTIVE',
    venue_id BIGINT NOT NULL,
    sport_type_id BIGINT NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP,
    CONSTRAINT fk_courts_venue
        FOREIGN KEY (venue_id) REFERENCES venues (id) ON DELETE CASCADE,
    CONSTRAINT fk_courts_sport_type
        FOREIGN KEY (sport_type_id) REFERENCES sport_types (id),
    CONSTRAINT ck_courts_status
        CHECK (status IN ('ACTIVE', 'INACTIVE', 'MAINTENANCE'))
);

CREATE TABLE IF NOT EXISTS hero_banners (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    url VARCHAR(500) NOT NULL,
    target_url VARCHAR(500),
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP
);

CREATE TABLE IF NOT EXISTS bookings (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_id BIGINT NOT NULL,
    court_id BIGINT NOT NULL,
    booking_date DATE NOT NULL,
    start_time TIME NOT NULL,
    end_time TIME NOT NULL,
    total_price NUMERIC(12, 2) NOT NULL,
    required_deposit NUMERIC(12, 2) NOT NULL,
    status VARCHAR(30) NOT NULL DEFAULT 'PENDING',
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP,
    CONSTRAINT fk_bookings_customer
        FOREIGN KEY (customer_id) REFERENCES users (id),
    CONSTRAINT fk_bookings_court
        FOREIGN KEY (court_id) REFERENCES courts (id),
    CONSTRAINT ck_bookings_status
        CHECK (status IN ('PENDING', 'CONFIRMED', 'CANCELLED', 'COMPLETED', 'EXPIRED')),
    CONSTRAINT ck_bookings_time
        CHECK (start_time < end_time),
    CONSTRAINT ck_bookings_amounts
        CHECK (
            total_price >= 0
            AND required_deposit >= 0
            AND required_deposit <= total_price
        )
);

CREATE TABLE IF NOT EXISTS owner_payment_accounts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    owner_id BIGINT NOT NULL,
    provider VARCHAR(30) NOT NULL,
    status VARCHAR(30) NOT NULL DEFAULT 'PENDING',
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP,
    CONSTRAINT fk_payment_accounts_owner
        FOREIGN KEY (owner_id) REFERENCES users (id),
    CONSTRAINT uq_payment_accounts_owner_provider
        UNIQUE (owner_id, provider),
    CONSTRAINT ck_payment_accounts_provider
        CHECK (provider IN ('MOMO', 'VNPAY')),
    CONSTRAINT ck_payment_accounts_status
        CHECK (status IN ('PENDING', 'ACTIVE', 'INACTIVE', 'SUSPENDED'))
);

CREATE TABLE IF NOT EXISTS momo_credentials (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    payment_account_id BIGINT NOT NULL UNIQUE,
    partner_code VARCHAR(100) NOT NULL UNIQUE,
    access_key VARCHAR(500) NOT NULL,
    secret_key VARCHAR(500) NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP,
    CONSTRAINT fk_momo_credentials_account
        FOREIGN KEY (payment_account_id)
        REFERENCES owner_payment_accounts (id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS vnpay_credentials (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    payment_account_id BIGINT NOT NULL UNIQUE,
    tmn_code VARCHAR(100) NOT NULL UNIQUE,
    hash_secret VARCHAR(500) NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP,
    CONSTRAINT fk_vnpay_credentials_account
        FOREIGN KEY (payment_account_id)
        REFERENCES owner_payment_accounts (id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS payments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    booking_id BIGINT NOT NULL,
    payment_account_id BIGINT,
    amount NUMERIC(12, 2) NOT NULL,
    payment_type VARCHAR(30) NOT NULL,
    status VARCHAR(30) NOT NULL DEFAULT 'PENDING',
    payment_method VARCHAR(30) NOT NULL,
    transaction_code VARCHAR(255) UNIQUE,
    paid_at TIMESTAMP,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP,
    CONSTRAINT fk_payments_booking
        FOREIGN KEY (booking_id) REFERENCES bookings (id) ON DELETE CASCADE,
    CONSTRAINT fk_payments_account
        FOREIGN KEY (payment_account_id) REFERENCES owner_payment_accounts (id),
    CONSTRAINT ck_payments_type
        CHECK (payment_type IN ('DEPOSIT', 'REMAINING', 'FULL_PAYMENT')),
    CONSTRAINT ck_payments_status
        CHECK (status IN ('PENDING', 'PAID', 'FAILED', 'REFUNDED', 'EXPIRED')),
    CONSTRAINT ck_payments_method
        CHECK (payment_method IN ('CASH', 'VNPAY', 'MOMO')),
    CONSTRAINT ck_payments_amount
        CHECK (amount >= 0)
);

CREATE INDEX IF NOT EXISTS idx_venues_status ON venues (status);
CREATE INDEX IF NOT EXISTS idx_venues_owner ON venues (owner_id);
CREATE INDEX IF NOT EXISTS idx_venues_lower_name ON venues (LOWER(name));
CREATE INDEX IF NOT EXISTS idx_courts_venue ON courts (venue_id);
CREATE INDEX IF NOT EXISTS idx_courts_sport_type ON courts (sport_type_id);
CREATE INDEX IF NOT EXISTS idx_bookings_customer ON bookings (customer_id);
CREATE INDEX IF NOT EXISTS idx_bookings_court_date ON bookings (court_id, booking_date);
CREATE INDEX IF NOT EXISTS idx_bookings_status ON bookings (status);
CREATE INDEX IF NOT EXISTS idx_payments_booking ON payments (booking_id);
CREATE INDEX IF NOT EXISTS idx_payments_account ON payments (payment_account_id);
CREATE INDEX IF NOT EXISTS idx_payments_status ON payments (status);
CREATE INDEX IF NOT EXISTS idx_payment_accounts_owner ON owner_payment_accounts (owner_id);
