"""create messageSource table

Revision ID: 109c55d5caa8
Revises: 3b3786cbd4cf
Create Date: 2026-07-21 15:54:51.531610

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '109c55d5caa8'
down_revision: Union[str, Sequence[str], None] = '3b3786cbd4cf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('message_sources',
    sa.Column('id', sa.Integer(), sa.Identity(always=False), nullable=False),
    sa.Column('message_id', sa.Integer(), nullable=False),
    sa.Column('chunk_id', sa.Integer(), nullable=False),
    sa.Column('rank', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['chunk_id'], ['ai.knowledge_chunks.id'], name=op.f('fk_message_sources_chunk_id_knowledge_chunks'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['message_id'], ['ai.messages.id'], name=op.f('fk_message_sources_message_id_messages'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_message_sources')),
    schema='ai'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('message_sources', schema='ai')
    # ### end Alembic commands ###
