"""create ingesion job table

Revision ID: a0d39e87a2bc
Revises: ed65f45134aa
Create Date: 2026-07-19 01:09:38.067896

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a0d39e87a2bc'
down_revision: Union[str, Sequence[str], None] = 'ed65f45134aa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ingestion_jobs',
    sa.Column('id', sa.Integer(), sa.Identity(always=False), nullable=False),
    sa.Column('document_id', sa.Integer(), nullable=False),
    sa.Column('job_type', sa.Enum('pdf_ingestion', 'database_ingestion', 'document_reindex', name='ingestion_job_type_enum', schema='ai'), nullable=False),
    sa.Column('status', sa.Enum('pending', 'processing', 'completed', 'failed', name='ingestion_job_status_enum', schema='ai'), server_default='pending', nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['document_id'], ['ai.knowledge_documents.id'], name=op.f('fk_ingestion_jobs_document_id_knowledge_documents'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ingestion_jobs')),
    schema='ai'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ingestion_jobs', schema='ai')
    # ### end Alembic commands ###
