"""create knowledge documents table

Revision ID: bf3fde0e3dea
Revises: 
Create Date: 2026-07-16 00:12:01.885671

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'bf3fde0e3dea'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('knowledge_documents',
    sa.Column('id', sa.Integer(), sa.Identity(always=False), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('source_type', sa.Enum('pdf', 'database', name='source_type_enum', schema='ai'), nullable=False),
    sa.Column('source_entity_type', sa.Enum('sport', 'exercise', 'training_plan', 'club', 'tournament', name='source_entity_type_enum', schema='ai'), nullable=True),
    sa.Column('source_entity_id', sa.String(length=255), nullable=True),
    sa.Column('source_uri', sa.Text(), nullable=True),
    sa.Column('original_filename', sa.String(length=255), nullable=True),
    sa.Column('checksum', sa.String(length=64), nullable=True),
    sa.Column('status', sa.Enum('pending', 'processing', 'ready', 'failed', 'archived', name='document_status_enum', schema='ai'), server_default='pending', nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('indexed_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_knowledge_documents')),
    schema='ai'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('knowledge_documents', schema='ai')
    # ### end Alembic commands ###
