spring.config.import=optional:file:.env[.properties]

spring.application.name=fieldmate
spring.profiles.default=dev

jwt.secret=${JWT_SECRET}
jwt.expiration=${JWT_EXPIRATION}

cloudinary.cloud-name=${CLOUDINARY_CLOUD_NAME}
cloudinary.api-key=${CLOUDINARY_API_KEY}
cloudinary.api-secret=${CLOUDINARY_API_SECRET}

springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.path=/v3/api-docs

booking.payment-timeout-minutes=15
booking.expiration-check-ms=60000

momo.base-url=${MOMO_BASE_URL}
momo.create-path=${MOMO_CREATE_PATH}

momo.redirect-url=${MOMO_REDIRECT_URL}
momo.ipn-url=${MOMO_IPN_URL}

momo.request-type=${MOMO_REQUEST_TYPE:captureWallet}
momo.language=${MOMO_LANGUAGE:vi}

vnpay.payment-url=${VNPAY_PAYMENT_URL}
vnpay.return-url=${VNPAY_RETURN_URL}
vnpay.frontend-return-url=${VNPAY_FRONTEND_RETURN_URL:http://localhost:3000/payment-return}
vnpay.ipn-url=${VNPAY_IPN_URL}

vnpay.version=${VNPAY_VERSION:2.1.0}
vnpay.command=${VNPAY_COMMAND:pay}
vnpay.order-type=${VNPAY_ORDER_TYPE:other}
vnpay.currency=${VNPAY_CURRENCY:VND}
vnpay.locale=${VNPAY_LOCALE:vn}
vnpay.expire-minutes=${VNPAY_EXPIRE_MINUTES:15}

credential.encryption-key=${CREDENTIAL_ENCRYPTION_KEY}

app.cors.allowed-origins=${CORS_ALLOWED_ORIGINS}
